### ISSUE TITLE
"Invalid # of arguments found on: "/send" is replied when clicking "/send"

### ISSUE THREAD

**Issue by biancady** [osiastedian/syscoin-tip-bot#14]
### STEPS TO REPRODUCE
1. Go to https://web.telegram.org/z/
2. Open Syscoin Bot
3. Click "hamburger" icon on the lower left side
   - Guide for /send command is displayed
4. Click "/send <address> <amount>"
5. Confirm message

### ACTUAL RESULT

- Invalid # of arguments found on: "[/send]()" is displayed

### EXPECTED RESULT

- A user friendly string should be replied by bot.
"Oops! You've inputted a wrong command. Please visit [t.me/SysCoinBot](http://t.me/SysCoinBot) for help with the bot."

### ADDITIONAL INFORMATION

- It should reply with a message that users can understand or reply with a link or like Seedit it replies with their 'Help' command and menu
- Issue also occurs on mobile and web app

![Incorrect string](https://user-images.githubusercontent.com/99260738/155318508-e1ee3539-c634-4668-af7a-134bb802b900.gif)

**Comment by osiastedian** [comment]
Fixed.`/send` is no longer available on menu.
