### ISSUE TITLE
"/ Menu" not working when group chat is newly created

### ISSUE THREAD

**Issue by biancady** [osiastedian/syscoin-tip-bot#25]
### PRECONDITION
1. Create a GC
2. Add users and SyscoinTip Bot

### STEPS TO REPRODUCE
1. Go to newly created groupchat
2. Press "/" button on the lower right

### ACTUAL RESULT

- "/help" and "/command" menu is no displayed

### EXPECTED RESULT

- "/help" and "/command" menu should be displayed

![menu not working](https://user-images.githubusercontent.com/99260738/156189623-994bfbdb-d2c0-4ac0-a761-354ec167d97b.gif)

**Comment by osiastedian** [comment]
![Screen Shot 2022-03-02 at 5 47 13 PM](https://user-images.githubusercontent.com/11253903/156337085-9d4ea80b-44e0-4c8b-bf78-860f19412f3d.png)

Now fixed.
