### ISSUE TITLE
Non-Admin can still view "Close" button of Airdrop Active

### ISSUE THREAD

**Issue by biancady** [osiastedian/syscoin-tip-bot#28]
### PRECONDITION
1. Create a group

### STEPS TO REPRODUCE
1. As Admin of the group --
- Input "Active_Airdrop" command
- Able to See "Join" and "Close" button
2. Switch account as a member of the group
-  Click 'Close' button

### ACTUAL RESULT

- Able to click or view "Close" button

### EXPECTED RESULT

- Must not be able to click or view "Close" button

**Comment by osiastedian** [comment]
Update Expected:

1. "Action Not allowed" when "close" button is clicked by Admin

**Comment by biancady** [comment]
Verified and Confirmed in Syscoin Mainnet.

![image](https://user-images.githubusercontent.com/99260738/157458456-c1618225-0a8a-4c20-b9c2-1b4db612db07.png)
